# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptions',
            name='site_name',
            field=models.CharField(default='Nome Sito', max_length=200, verbose_name='Nome del Sito'),
        ),
    ]
