# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161205_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptions',
            name='modenese_en',
            field=models.TextField(default='Modenese EN', verbose_name='Testo per pagina Modenese in Inglese'),
        ),
        migrations.AddField(
            model_name='descriptions',
            name='modenese_id',
            field=models.TextField(default='Modenese IT', verbose_name='Testo per pagina Modenese in Italiano'),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='header_background',
            field=models.ImageField(upload_to='uploads/images/descriptions', verbose_name='Immagine di Sfondo (Testata)'),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='logo',
            field=models.ImageField(upload_to='uploads/images/descriptions', verbose_name='Logo Principale del Sito'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/images/products', verbose_name='Immagine'),
        ),
    ]
