# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161213_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptions',
            old_name='modenese_id',
            new_name='modenese_it',
        ),
    ]
